### ISSUE TITLE
TALOS Security Advisory for Gerbv (TALOS-2021-1402)

### ISSUE THREAD

**Issue by CiscoTalos** [gerbv/gerbv#30]
Hello, 
The Cisco Talos team found a security vulnerability affecting Gerbv products. As this is a sensitive security issue, please advise if you can mark the issue private in Github before we include the details of the report.

For further information about the Cisco Vendor Vulnerability Reporting and Disclosure Policy please refer to this document which also links to our public PGP key. https://tools.cisco.com/security/center/resources/vendor_vulnerability_policy.html Please CC vulndev@cisco.com all correspondence related to this issue.

**Comment by CiscoTalos** [comment]
You can find the CVE in the advisory, this one is assigned CVE-2021-40391. You can publish our advisory on the mailing lists. We will publish our advisories at [https://talosintelligence.com/vulnerability_reports](https://talosintelligence.com/vulnerability_reports).

We're however a little confused about what the official version of gerbv is. Since you and the version on sourceforge both use the same name, is this repository a fork of that version or are you now the official version and have you worked that out with the distros? 
Based on our current understanding, we've been waiting for a reply from the sourceforge version before we publish.

**Comment by ooxi** [comment]
> We're however a little confused about what the official version of gerbv is. Since you and the version on sourceforge both use the same name, is this repository a fork of that version or are you now the official version and have you worked that out with the distros?
>
> Based on our current understanding, we've been waiting for a reply from the sourceforge version before we publish.

gerbv's history is a bit convoluted. Originally created by Stefan Petersen (@spe-ciellt) the software was then maintained on SourceForge and (gEDA project](http://gerbv.geda-project.org/). However the maintainers after Stefan became unresponsive which is why patches started piling up on SourceForge.

Since the software is still very useful, I created this GitHub organization in August and [invited everybody](https://sourceforge.net/p/gerbv/mailman/message/37343011/) from SourceForge to join. On of the [first replies](https://sourceforge.net/p/gerbv/mailman/message/37343047/) was from Stefan himself who blessed this move and since then the offer was taken up by multiple contributors like @eyal0 and @efa.

Since we have not created a formal release up until last week, we have not yet informed distributions, but will do so in the near future.

Hope this clears up the constellation for you :-)

**Comment by spe-ciellt** [comment]
I also responded on the ticket on Sourceforge to refer to this place: https://sourceforge.net/p/gerbv/bugs/259/

**Comment by CiscoTalos** [comment]
Thank you for the clarification. We will prepare disclosure on our end.

**Comment by CiscoTalos** [comment]
[TALOS-2021-1402.poc.zip](https://github.com/gerbv/gerbv/files/7477463/TALOS-2021-1402.poc.zip)

**Comment by ooxi** [comment]
@CiscoTalos we now published [v2.7.1](https://github.com/gerbv/gerbv/releases/tag/v2.7.1) as well as [v2.8.0](https://github.com/gerbv/gerbv/releases/tag/v2.8.0), both carrying the patch fixing this issue.

Therefore I close this issue. Feel free to reopen if the need arises and thank you again!

Btw. it would be great if you could link to those releases in your advisory in order to let users know how to obtain the fix.
