### ISSUE TITLE
migrate issues from sourceforge

### ISSUE THREAD

**Issue by ferdymercury** [gerbv/gerbv#66]
It might be useful to migrate these 116 issues into GitHub:

https://sourceforge.net/p/gerbv/bugs/
https://sourceforge.net/p/gerbv/feature-requests/

using e.g.:
https://github.com/itamarc/gosf2github

and submit a bug report and feature request on SF informing users about this maintained fork.

**Comment by ooxi** [comment]
Thank you for your suggestion @ferdymercury! I already considered doing this, however decided against doing so because of two reasons:

1. Our capacity is very limited. I therefore prefer focusing on issues which people are currently experiencing
2. It's much easier to triangulate an issue or even enable users to create PRs, if you work with them. Thus migrating issues created years ago on a different platform might not carry much use

Before carrying issues, I would carry pull requests over. And we have already started doing to.

If you find certain issues on SourceForge which are relevant to you or the general audience, feel free to open them here and work with us on resolving them :-)
